import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getCurrentUser } from '@/lib/auth'

/**
 * GET /api/developer/apps/[id]
 * Return single app details. Auth required, must own the app.
 */
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const user = await getCurrentUser()
    if (!user) {
      return NextResponse.json({ error: 'Login required' }, { status: 401 })
    }

    const { id } = await params

    const app = await prisma.app.findUnique({
      where: { id },
      include: {
        circle: true,
        _count: { select: { feedbacks: true } },
      },
    })

    if (!app) {
      return NextResponse.json({ error: 'App not found' }, { status: 404 })
    }

    if (app.developerId !== user.id) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    return NextResponse.json({ success: true, data: app })
  } catch (error) {
    console.error('Get app detail failed:', error)
    return NextResponse.json({ error: 'Query failed' }, { status: 500 })
  }
}

/**
 * PUT /api/developer/apps/[id]
 * Update app fields: clientId, links, description, etc.
 */
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const user = await getCurrentUser()
    if (!user) {
      return NextResponse.json({ error: 'Login required' }, { status: 401 })
    }

    const { id } = await params

    const app = await prisma.app.findUnique({ where: { id } })
    if (!app) {
      return NextResponse.json({ error: 'App not found' }, { status: 404 })
    }
    if (app.developerId !== user.id) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    const body = await request.json()
    const {
      name,
      description,
      clientId,
      website,
      logo,
      metadata,
      shortPrompt,
      detailedPrompt,
      systemSummary,
      status,
    } = body

    // Status validation: only active, inactive, archived. Archived is terminal.
    const VALID_STATUSES = ['active', 'inactive', 'archived'] as const
    if (status !== undefined) {
      if (!VALID_STATUSES.includes(status)) {
        return NextResponse.json({ error: `Invalid status. Must be one of: ${VALID_STATUSES.join(', ')}` }, { status: 400 })
      }
      if (status === 'archived' && app.status === 'archived') {
        return NextResponse.json({ error: 'App is already archived' }, { status: 400 })
      }
      if (app.status === 'archived') {
        return NextResponse.json({ error: 'Cannot change status of archived app' }, { status: 400 })
      }
    }

    if (clientId !== undefined && clientId !== app.clientId) {
      const isAutoGenerated = app.clientId?.startsWith('app-') ?? true
      if (!isAutoGenerated) {
        return NextResponse.json(
          { error: 'Client ID 已绑定 SecondMe 平台，不可修改。如需变更请联系管理员。' },
          { status: 403 }
        )
      }
      if (clientId) {
        const existing = await prisma.app.findUnique({ where: { clientId } })
        if (existing && existing.id !== id) {
          return NextResponse.json({ error: 'Client ID already in use' }, { status: 409 })
        }
      }
    }

    const updated = await prisma.app.update({
      where: { id },
      data: {
        ...(name !== undefined && { name }),
        ...(description !== undefined && { description }),
        ...(clientId !== undefined && { clientId: clientId || null }),
        ...(website !== undefined && { website }),
        ...(logo !== undefined && { logo }),
        ...(metadata !== undefined && { metadata }),
        ...(shortPrompt !== undefined && { shortPrompt }),
        ...(detailedPrompt !== undefined && { detailedPrompt }),
        ...(systemSummary !== undefined && { systemSummary }),
        ...(status !== undefined && { status }),
      },
      include: { circle: true },
    })

    return NextResponse.json({ success: true, data: updated })
  } catch (error) {
    console.error('Update app failed:', error)
    return NextResponse.json({ error: 'Update failed' }, { status: 500 })
  }
}
